# Generated by Django 5.2.5 on 2025-08-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataclass',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dataclass',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
