# Generated by Django 5.2.5 on 2025-08-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dataclass_date_dataclass_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataclass',
            name='firstName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataclass',
            name='lastName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
