# Generated by Django 5.2.5 on 2025-08-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dataclass_firstname_alter_dataclass_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataclass',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataclass',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
