# Generated by Django 5.2.5 on 2025-09-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dataclass_email_dataclass_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataclass',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
